### ISSUE TITLE
[section]빅배너-arrow position 오류

### ISSUE THREAD

**Issue by 5wintaek** [likelion-lab1/vanilla-project#27]
# Issue : 버그보고
## 버그가 발생하는 페이지와 문제점
화살표 수치가 피그마에 나와있는것처럼 하려고 적용해보려는데 피그마에서 나온 빅배너 수치는 width : 1920 , height 370 입니다.
이게 max-width 가 1920 인거 같아요. 해상도는 사용자가 어떤 해상도를 가졌냐에 따라 다르니깐요 
따라서 버튼에 위치를 그냥 제가 임의로 조정하는게 맞나 싶어서 올립니다

```CSS
.container {
  width: 100%;
  min-width: 1050px;
  height: 370px;
}


.swiper-button-next{ 
  background: url(./img/Arrow.png) 50% 50% no-repeat;
  transform: rotate(180deg);
  position: absolute;
  top: 0px;
  bottom: 0px;
  left: 50%;
  height: 52px;
  width: 52px;
  margin: auto 0px auto 590px;
}

.swiper-button-prev{
  background: url(./img/Arrow.png)  no-repeat;
  position: absolute;
  top: 0px;
  bottom: 0px;
  right: 50%;
  height: 52px;
  width: 52px;
  margin: auto 590px auto 0px  
}
```

### 스크린샷

![image](https://user-images.githubusercontent.com/109938280/215644088-2b900f8a-9839-471a-af00-d3e0cb9b5f10.png)

## 해결방안

button prev, next 부분의 margin 값을 제가 임의로 조정하려고 합니다
